// Generated by gencpp from file admittance_controller/parameter_srv.msg
// DO NOT EDIT!


#ifndef ADMITTANCE_CONTROLLER_MESSAGE_PARAMETER_SRV_H
#define ADMITTANCE_CONTROLLER_MESSAGE_PARAMETER_SRV_H

#include <ros/service_traits.h>


#include <admittance_controller/parameter_srvRequest.h>
#include <admittance_controller/parameter_srvResponse.h>


namespace admittance_controller
{

struct parameter_srv
{

typedef parameter_srvRequest Request;
typedef parameter_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct parameter_srv
} // namespace admittance_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::admittance_controller::parameter_srv > {
  static const char* value()
  {
    return "70632979ff89b96bd0760110d8fca5c4";
  }

  static const char* value(const ::admittance_controller::parameter_srv&) { return value(); }
};

template<>
struct DataType< ::admittance_controller::parameter_srv > {
  static const char* value()
  {
    return "admittance_controller/parameter_srv";
  }

  static const char* value(const ::admittance_controller::parameter_srv&) { return value(); }
};


// service_traits::MD5Sum< ::admittance_controller::parameter_srvRequest> should match
// service_traits::MD5Sum< ::admittance_controller::parameter_srv >
template<>
struct MD5Sum< ::admittance_controller::parameter_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::admittance_controller::parameter_srv >::value();
  }
  static const char* value(const ::admittance_controller::parameter_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::admittance_controller::parameter_srvRequest> should match
// service_traits::DataType< ::admittance_controller::parameter_srv >
template<>
struct DataType< ::admittance_controller::parameter_srvRequest>
{
  static const char* value()
  {
    return DataType< ::admittance_controller::parameter_srv >::value();
  }
  static const char* value(const ::admittance_controller::parameter_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::admittance_controller::parameter_srvResponse> should match
// service_traits::MD5Sum< ::admittance_controller::parameter_srv >
template<>
struct MD5Sum< ::admittance_controller::parameter_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::admittance_controller::parameter_srv >::value();
  }
  static const char* value(const ::admittance_controller::parameter_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::admittance_controller::parameter_srvResponse> should match
// service_traits::DataType< ::admittance_controller::parameter_srv >
template<>
struct DataType< ::admittance_controller::parameter_srvResponse>
{
  static const char* value()
  {
    return DataType< ::admittance_controller::parameter_srv >::value();
  }
  static const char* value(const ::admittance_controller::parameter_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ADMITTANCE_CONTROLLER_MESSAGE_PARAMETER_SRV_H
