// Generated by gencpp from file admittance_controller/parameter_srvResponse.msg
// DO NOT EDIT!


#ifndef ADMITTANCE_CONTROLLER_MESSAGE_PARAMETER_SRVRESPONSE_H
#define ADMITTANCE_CONTROLLER_MESSAGE_PARAMETER_SRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace admittance_controller
{
template <class ContainerAllocator>
struct parameter_srvResponse_
{
  typedef parameter_srvResponse_<ContainerAllocator> Type;

  parameter_srvResponse_()
    : success(false)  {
    }
  parameter_srvResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::admittance_controller::parameter_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::admittance_controller::parameter_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct parameter_srvResponse_

typedef ::admittance_controller::parameter_srvResponse_<std::allocator<void> > parameter_srvResponse;

typedef boost::shared_ptr< ::admittance_controller::parameter_srvResponse > parameter_srvResponsePtr;
typedef boost::shared_ptr< ::admittance_controller::parameter_srvResponse const> parameter_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::admittance_controller::parameter_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::admittance_controller::parameter_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::admittance_controller::parameter_srvResponse_<ContainerAllocator1> & lhs, const ::admittance_controller::parameter_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::admittance_controller::parameter_srvResponse_<ContainerAllocator1> & lhs, const ::admittance_controller::parameter_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace admittance_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::admittance_controller::parameter_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::admittance_controller::parameter_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::admittance_controller::parameter_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::admittance_controller::parameter_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::admittance_controller::parameter_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::admittance_controller::parameter_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::admittance_controller::parameter_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::admittance_controller::parameter_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::admittance_controller::parameter_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "admittance_controller/parameter_srvResponse";
  }

  static const char* value(const ::admittance_controller::parameter_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::admittance_controller::parameter_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
"\n"
;
  }

  static const char* value(const ::admittance_controller::parameter_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::admittance_controller::parameter_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct parameter_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::admittance_controller::parameter_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::admittance_controller::parameter_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ADMITTANCE_CONTROLLER_MESSAGE_PARAMETER_SRVRESPONSE_H
