// Generated by gencpp from file szj_controller/pointData.msg
// DO NOT EDIT!


#ifndef SZJ_CONTROLLER_MESSAGE_POINTDATA_H
#define SZJ_CONTROLLER_MESSAGE_POINTDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace szj_controller
{
template <class ContainerAllocator>
struct pointData_
{
  typedef pointData_<ContainerAllocator> Type;

  pointData_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , rx(0.0)
    , ry(0.0)
    , rz(0.0)  {
    }
  pointData_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , rx(0.0)
    , ry(0.0)
    , rz(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _rx_type;
  _rx_type rx;

   typedef double _ry_type;
  _ry_type ry;

   typedef double _rz_type;
  _rz_type rz;





  typedef boost::shared_ptr< ::szj_controller::pointData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::szj_controller::pointData_<ContainerAllocator> const> ConstPtr;

}; // struct pointData_

typedef ::szj_controller::pointData_<std::allocator<void> > pointData;

typedef boost::shared_ptr< ::szj_controller::pointData > pointDataPtr;
typedef boost::shared_ptr< ::szj_controller::pointData const> pointDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::szj_controller::pointData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::szj_controller::pointData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::szj_controller::pointData_<ContainerAllocator1> & lhs, const ::szj_controller::pointData_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.rx == rhs.rx &&
    lhs.ry == rhs.ry &&
    lhs.rz == rhs.rz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::szj_controller::pointData_<ContainerAllocator1> & lhs, const ::szj_controller::pointData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace szj_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::szj_controller::pointData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::szj_controller::pointData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::szj_controller::pointData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::szj_controller::pointData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::szj_controller::pointData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::szj_controller::pointData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::szj_controller::pointData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88d995302418aa13534aa14fc9aeed94";
  }

  static const char* value(const ::szj_controller::pointData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88d995302418aa13ULL;
  static const uint64_t static_value2 = 0x534aa14fc9aeed94ULL;
};

template<class ContainerAllocator>
struct DataType< ::szj_controller::pointData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "szj_controller/pointData";
  }

  static const char* value(const ::szj_controller::pointData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::szj_controller::pointData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 rx\n"
"float64 ry\n"
"float64 rz\n"
;
  }

  static const char* value(const ::szj_controller::pointData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::szj_controller::pointData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.rx);
      stream.next(m.ry);
      stream.next(m.rz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pointData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::szj_controller::pointData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::szj_controller::pointData_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "rx: ";
    Printer<double>::stream(s, indent + "  ", v.rx);
    s << indent << "ry: ";
    Printer<double>::stream(s, indent + "  ", v.ry);
    s << indent << "rz: ";
    Printer<double>::stream(s, indent + "  ", v.rz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SZJ_CONTROLLER_MESSAGE_POINTDATA_H
