# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from szj_demo/AdmStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class AdmStatus(genpy.Message):
  _md5sum = "0eec79276a71eca81aff53272305516b"
  _type = "szj_demo/AdmStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 forceTarget
float64 forceNow
float64 paraB
float64 deltaB
float64 zdd
float64 commandVel
float64 actualVel"""
  __slots__ = ['forceTarget','forceNow','paraB','deltaB','zdd','commandVel','actualVel']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       forceTarget,forceNow,paraB,deltaB,zdd,commandVel,actualVel

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AdmStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.forceTarget is None:
        self.forceTarget = 0.
      if self.forceNow is None:
        self.forceNow = 0.
      if self.paraB is None:
        self.paraB = 0.
      if self.deltaB is None:
        self.deltaB = 0.
      if self.zdd is None:
        self.zdd = 0.
      if self.commandVel is None:
        self.commandVel = 0.
      if self.actualVel is None:
        self.actualVel = 0.
    else:
      self.forceTarget = 0.
      self.forceNow = 0.
      self.paraB = 0.
      self.deltaB = 0.
      self.zdd = 0.
      self.commandVel = 0.
      self.actualVel = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.forceTarget, _x.forceNow, _x.paraB, _x.deltaB, _x.zdd, _x.commandVel, _x.actualVel))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 56
      (_x.forceTarget, _x.forceNow, _x.paraB, _x.deltaB, _x.zdd, _x.commandVel, _x.actualVel,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.forceTarget, _x.forceNow, _x.paraB, _x.deltaB, _x.zdd, _x.commandVel, _x.actualVel))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 56
      (_x.forceTarget, _x.forceNow, _x.paraB, _x.deltaB, _x.zdd, _x.commandVel, _x.actualVel,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
